'use client'
import Link from 'next/link'
import { ArrowLeft, Bot, Check, CircleDollarSign } from 'lucide-react'
import { Nav } from '../page'
import { useState } from 'react'
import { applyMove, botMove, getLegalMoves, indexAt, initialBoard, playable, type Piece } from '@/lib/draughts'
const levels=[['Easy','Random legal moves'],['Medium','Capture priority'],['Hard','Position-aware bot']]
export default function PracticePage(){const [level,setLevel]=useState('Medium'),[started,setStarted]=useState(false),[board,setBoard]=useState<Piece[]>(initialBoard),[selected,setSelected]=useState<number|null>(null),[turn,setTurn]=useState<'black'|'white'>('black'),[status,setStatus]=useState('Black to move · captures are compulsory')
function reset(){setBoard(initialBoard());setTurn('black');setSelected(null);setStarted(true);setStatus('Black to move · captures are compulsory')}
function click(row:number,col:number){if(!started||turn!=='black')return;const at=indexAt(board,row,col);const moves=selected===null?[]:getLegalMoves(board,'black',selected);const chosen=moves.find(m=>Math.floor(m.to/10)===row&&m.to%10===col);if(chosen){const next=applyMove(board,chosen);setBoard(next);setSelected(null);setTurn('white');setStatus('White (Bot) thinking…');window.setTimeout(()=>{const move=botMove(next,level);if(!move){setTurn('black');setStatus('You win.');return}setBoard(applyMove(next,move));setTurn('black');setStatus('Black to move · captures are compulsory')},800);return}if(at>=0&&board[at].side==='black'&&getLegalMoves(board,'black',at).length){setSelected(at)}else setSelected(null)}
const destinations=new Set((selected===null?[]:getLegalMoves(board,'black',selected)).map(m=>m.to))
return <main className="min-h-screen bg-black text-white"><Nav/><div className="mx-auto max-w-7xl px-5 pb-24 pt-12 lg:px-10"><Link href="/" className="mb-10 inline-flex items-center gap-2 text-sm text-zinc-500"><ArrowLeft className="size-4"/>Back home</Link><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><section><p className="text-xs uppercase tracking-[0.2em] text-zinc-500">Free forever</p><h1 className="mt-3 text-5xl font-semibold tracking-[-0.05em]">Sharpen your game.</h1><p className="mt-5 max-w-md leading-7 text-zinc-400">International Draughts on a full 10×10 board. No entry fee, no limits.</p><div className="mt-8 flex items-center gap-2 text-sm text-zinc-400"><CircleDollarSign className="size-4 text-[#ffd700]"/>Costs 0 coins to play</div><div className="mt-10 flex flex-col gap-3">{levels.map(([name,copy])=><button key={name} onClick={()=>setLevel(name)} className={`flex items-center justify-between rounded-2xl border p-4 text-left ${level===name?'border-white bg-white text-black':'border-white/10 bg-zinc-950'}`}><span className="flex items-center gap-3"><Bot className="size-5"/><span><strong className="block text-sm">{name} Bot</strong><small className={level===name?'text-black/55':'text-zinc-500'}>{copy}</small></span></span>{level===name&&<Check className="size-4"/>}</button>)}</div><button onClick={reset} className="mt-6 w-full rounded-xl bg-white py-4 text-sm font-semibold text-black">{started?'Restart practice':'Start practice'}</button></section><section><p className="mb-3 text-center text-sm text-zinc-500">{status}</p><div className="mx-auto grid aspect-square w-full max-w-[560px] grid-cols-10 overflow-hidden rounded-2xl border-8 border-zinc-800 bg-[#e9e1d0]">{Array.from({length:100},(_,i)=>{const row=Math.floor(i/10),col=i%10,at=indexAt(board,row,col),piece=at>=0?board[at]:null,target=destinations.has(row*10+col);return <button aria-label={`Square ${row+1}, ${col+1}`} key={i} onClick={()=>click(row,col)} className={`relative aspect-square ${playable(row,col)?'bg-[#b58d5a]':'bg-[#f0dfbe]'}`}>{piece&&<span className={`absolute inset-[14%] rounded-full border-4 shadow-lg ${piece.side==='black'?'border-zinc-950 bg-zinc-700':'border-white bg-zinc-100'} ${piece.king?'ring-4 ring-[#ffd700]':''} ${selected===at?'ring-4 ring-blue-400':''}`}/>} {target&&<span className="absolute left-1/2 top-1/2 size-4 -translate-x-1/2 -translate-y-1/2 rounded-full bg-emerald-400 ring-4 ring-emerald-400/25"/>}</button>})}</div><p className="mt-4 text-center text-xs text-zinc-500">Black moves first · Capture the most pieces possible · Gold ring = king</p></section></div></div></main>}
