'use client'

import Link from 'next/link'
import { useRouter, useSearchParams } from 'next/navigation'
import { Suspense, useMemo, useState } from 'react'
import { addBalance, canAfford, deductBalance } from '@/lib/wallet'
import { formatCoins, getBot } from '@/lib/bots'
import { applyMove, Board, chooseMove, createBoard, getMoves, logCounts, Side, winner } from '@/lib/checkers'

function Match() {
  const router = useRouter(); const params = useSearchParams(); const bot = useMemo(() => getBot(params.get('bot') ?? ''), [params])
  const [board, setBoard] = useState<Board>(() => createBoard()); const [selected, setSelected] = useState<[number,number] | null>(null); const [started, setStarted] = useState(false); const [turn, setTurn] = useState<Side>('red'); const [message, setMessage] = useState('Start the match to play.')
  if (!bot) return <main className="grid min-h-screen place-items-center bg-[#080808] text-white"><div><h1 className="text-3xl font-black">Bot not found</h1><Link href="/arena" className="mt-4 inline-block text-[#d6ff38]">Back to Arena</Link></div></main>
  const moves = getMoves(board, 'red')
  const start = () => { if (!canAfford(bot.buyIn)) { router.push('/buy-coins'); return } if (deductBalance(bot.buyIn)) { setStarted(true); setMessage('Your turn. Captures are mandatory.') } }
  const click = (r:number,c:number) => { if (!started || turn !== 'red') return; const move = moves.find(item => item.path[0][0] === selected?.[0] && item.path[0][1] === selected?.[1] && item.path.at(-1)?.[0] === r && item.path.at(-1)?.[1] === c); if (!move) { if (board[r][c]?.side === 'red') setSelected([r,c]); return }; const next = applyMove(board, move); setBoard(next); setSelected(null); logCounts(next, 'black'); const botMove = chooseMove(next, 'black', bot.id === 'finn' ? 2 : bot.id === 'john' || bot.id === 'arthur' ? 3 : bot.id === 'stringer' || bot.id === 'avon' ? 4 : 5, bot.id === 'finn' ? 0.3 : 0); if (!botMove || winner(next,'red') === 'red') { addBalance(bot.payout); setMessage(`Victory. ${formatCoins(bot.payout)} coins paid.`); setTurn('black'); return }; window.setTimeout(() => { const after = applyMove(next, botMove); setBoard(after); setTurn('red'); logCounts(after,'red'); setMessage(winner(after,'red') === 'black' ? 'Defeat. Try again.' : 'Your turn.') }, 300) }
  return <main className="min-h-screen bg-[#080808] px-4 py-8 text-white"><div className="mx-auto max-w-3xl"><div className="flex justify-between"><Link href="/arena" className="text-sm text-white/50">Back to Arena</Link><span className="text-sm font-bold text-[#d6ff38]">{bot.name} · {formatCoins(bot.buyIn)}</span></div><h1 className="mt-8 text-4xl font-black">You vs {bot.name}</h1><p className="mt-2 text-white/50">International 10×10 · backward captures · flying kings · chain capture</p><p className="mt-5 font-bold text-[#d6ff38]">{message}</p><div className="mx-auto mt-5 grid aspect-square max-w-[600px] grid-cols-10 overflow-hidden rounded-xl border border-white/10">{board.map((row,r)=>row.map((cell,c)=>{const dark=(r+c)%2===1;const sel=selected?.[0]===r&&selected?.[1]===c;return <button key={`${r}-${c}`} onClick={()=>click(r,c)} className={`grid place-items-center ${dark?'bg-[#9b9864]':'bg-[#e7dfb7]'} ${sel?'ring-4 ring-inset ring-[#d6ff38]':''}`}>{cell&&<span className={`size-[62%] rounded-full border-4 ${cell.side==='red'?'border-red-300 bg-red-600':'border-zinc-500 bg-zinc-900'} ${cell.king?'ring-4 ring-yellow-300':''}`}/>}</button>}))}</div>{!started&&<button onClick={start} className="mt-6 w-full rounded-xl bg-[#d6ff38] px-5 py-4 font-black text-black">PLAY FOR {formatCoins(bot.buyIn)} COINS</button>}</div></main>
}
export default function PlayPage(){return <Suspense fallback={<main className="grid min-h-screen place-items-center bg-[#080808] text-white">Loading match...</main>}><Match/></Suspense>}
