'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { ArrowRight, Coins, Shield, Trophy, Zap } from 'lucide-react'
import { bots, formatCoins, PLAYER_WIN_RATE } from '@/lib/bots'
import { deductBalance, getBalance } from '@/lib/wallet'

export default function ArenaPage() {
  const [balance, setBalance] = useState(0)
  useEffect(() => { const sync = () => setBalance(getBalance()); sync(); window.addEventListener('wallet-change', sync); return () => window.removeEventListener('wallet-change', sync) }, [])
  return <main className="min-h-screen bg-[#080808] text-white"><header className="border-b border-white/10 bg-[#0c0c0c]/95"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><Link href="/arena" className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#d6ff38] text-black"><Shield size={18} /></span><span className="text-sm font-black uppercase tracking-[0.22em]">Daily Checkers</span></Link><Link href="/buy-coins" className="flex items-center gap-2 rounded-full border border-[#d6ff38]/30 bg-[#d6ff38]/10 px-4 py-2 text-sm font-bold text-[#d6ff38]"><Coins size={16} /> {formatCoins(balance)} coins <ArrowRight size={15} /></Link></div></header><section className="mx-auto max-w-6xl px-5 pb-16 pt-14"><div className="mb-12 max-w-2xl"><p className="mb-4 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.25em] text-[#d6ff38]"><Zap size={14} fill="currentColor" /> Live 1v1 arena</p><h1 className="text-4xl font-black sm:text-6xl">Pick your opponent.<br /><span className="text-white/45">Own the board.</span></h1><p className="mt-5 text-white/50">Seven bots. One shot. Put your coins on the line.</p><div className="mt-6 flex gap-3 text-xs font-bold uppercase tracking-wider text-white/45"><span className="rounded-full border border-white/10 px-3 py-2">{PLAYER_WIN_RATE}% player win rate</span><span className="rounded-full border border-white/10 px-3 py-2">Instant payouts</span></div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{bots.map((bot, index) => { const affordable = balance >= bot.buyIn; return <article key={bot.id} className="rounded-2xl border border-white/10 bg-[#111] p-5"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><div className="grid size-12 place-items-center rounded-full bg-[#1c1c1c] text-xl font-black text-[#d6ff38]">{bot.name[0]}</div><div><h2 className="text-lg font-extrabold">{bot.name}</h2><p className="text-xs uppercase tracking-widest text-white/35">{bot.tier} · 0{index + 1}</p></div></div><Trophy size={17} className="text-white/25" /></div><div className="mt-7 grid grid-cols-2 gap-3 rounded-xl bg-black/30 p-3"><div><p className="text-[10px] uppercase text-white/35">Entry</p><p className="text-lg font-black">{formatCoins(bot.buyIn)}</p></div><div><p className="text-[10px] uppercase text-white/35">Win</p><p className="text-lg font-black text-[#d6ff38]">{formatCoins(bot.payout)}</p></div></div><Link href={affordable ? `/play?bot=${bot.id}` : '/buy-coins'} onClick={(e) => { if (affordable && !deductBalance(bot.buyIn)) e.preventDefault() }} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#d6ff38] px-4 py-3 text-xs font-black uppercase tracking-[0.18em] text-black">{affordable ? 'Play' : 'Get coins'} <ArrowRight size={15} /></Link></article> })}</div></section></main>
}
